"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 08:42:56.105162

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_he', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('house_rules', sa.Text(), nullable=False),
    sa.Column('neighborhood', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('google_maps_url', sa.String(length=1000), nullable=False),
    sa.Column('max_guests', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('beds', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cleaning_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_nights', sa.Integer(), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=False),
    sa.Column('check_out_time', sa.Time(), nullable=False),
    sa.Column('seo_title', sa.String(length=200), nullable=False),
    sa.Column('seo_description', sa.String(length=400), nullable=False),
    sa.Column('airbnb_ical_url', sa.String(length=1000), nullable=False),
    sa.Column('ical_export_token', sa.String(length=64), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_success', sa.Boolean(), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('last_sync_events', sa.Integer(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ical_export_token')
    )
    op.create_index(op.f('ix_apartments_active'), 'apartments', ['active'], unique=False)
    op.create_index(op.f('ix_apartments_neighborhood'), 'apartments', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_apartments_slug'), 'apartments', ['slug'], unique=True)
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=200), nullable=False),
    sa.Column('site_name_he', sa.String(length=200), nullable=False),
    sa.Column('logo_url', sa.String(length=1000), nullable=False),
    sa.Column('hero_image_url', sa.String(length=1000), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('instagram_url', sa.String(length=500), nullable=False),
    sa.Column('facebook_url', sa.String(length=500), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('about_text_en', sa.Text(), nullable=False),
    sa.Column('about_text_he', sa.Text(), nullable=False),
    sa.Column('footer_text_en', sa.Text(), nullable=False),
    sa.Column('footer_text_he', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('apartment_amenities',
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('apartment_id', 'amenity_id')
    )
    op.create_table('apartment_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=300), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('alt_text', sa.String(length=300), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apartment_images_apartment_id'), 'apartment_images', ['apartment_id'], unique=False)
    op.create_table('apartment_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('house_rules', sa.Text(), nullable=True),
    sa.Column('neighborhood', sa.String(length=120), nullable=True),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apartment_id', 'locale', name='uq_apartment_locale')
    )
    op.create_index(op.f('ix_apartment_translations_apartment_id'), 'apartment_translations', ['apartment_id'], unique=False)
    op.create_table('booking_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('estimated_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('check_out > check_in', name='ck_inquiry_dates_order'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_inquiries_apartment_id'), 'booking_inquiries', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_booking_inquiries_status'), 'booking_inquiries', ['status'], unique=False)
    op.create_table('calendar_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('events_imported', sa.Integer(), nullable=False),
    sa.Column('events_created', sa.Integer(), nullable=False),
    sa.Column('events_updated', sa.Integer(), nullable=False),
    sa.Column('events_removed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_sync_logs_apartment_id'), 'calendar_sync_logs', ['apartment_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=True),
    sa.Column('guest_name', sa.String(length=200), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=False),
    sa.Column('guest_phone', sa.String(length=50), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('nightly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cleaning_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('check_out > check_in', name='ck_booking_dates_order'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inquiry_id'], ['booking_inquiries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquiry_id')
    )
    op.create_index(op.f('ix_bookings_apartment_id'), 'bookings', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_bookings_check_in'), 'bookings', ['check_in'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('blocked_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_uid', sa.String(length=500), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='ck_block_dates_order'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apartment_id', 'source', 'external_uid', name='uq_block_external_uid'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index('ix_blocked_dates_apartment_range', 'blocked_dates', ['apartment_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_blocked_dates_source'), 'blocked_dates', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blocked_dates_source'), table_name='blocked_dates')
    op.drop_index('ix_blocked_dates_apartment_range', table_name='blocked_dates')
    op.drop_table('blocked_dates')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_check_in'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_apartment_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_calendar_sync_logs_apartment_id'), table_name='calendar_sync_logs')
    op.drop_table('calendar_sync_logs')
    op.drop_index(op.f('ix_booking_inquiries_status'), table_name='booking_inquiries')
    op.drop_index(op.f('ix_booking_inquiries_apartment_id'), table_name='booking_inquiries')
    op.drop_table('booking_inquiries')
    op.drop_index(op.f('ix_apartment_translations_apartment_id'), table_name='apartment_translations')
    op.drop_table('apartment_translations')
    op.drop_index(op.f('ix_apartment_images_apartment_id'), table_name='apartment_images')
    op.drop_table('apartment_images')
    op.drop_table('apartment_amenities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_apartments_slug'), table_name='apartments')
    op.drop_index(op.f('ix_apartments_neighborhood'), table_name='apartments')
    op.drop_index(op.f('ix_apartments_active'), table_name='apartments')
    op.drop_table('apartments')
    op.drop_table('amenities')
    # ### end Alembic commands ###
