"""apartment owner whatsapp

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-08 12:19:41.813238

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default fills existing rows; the app supplies the value from then on.
    op.add_column(
        'apartments',
        sa.Column('owner_whatsapp', sa.String(length=50), nullable=False, server_default=''),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'owner_whatsapp')
    # ### end Alembic commands ###
