"""inquiry channel

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-08 12:47:20.631109

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'booking_inquiries',
        sa.Column('channel', sa.String(length=16), nullable=False, server_default='form'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_inquiries', 'channel')
    # ### end Alembic commands ###
