"""apartment owner email

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-08 13:03:51.743876

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'apartments',
        sa.Column('owner_email', sa.String(length=255), nullable=False, server_default=''),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'owner_email')
    # ### end Alembic commands ###
