"""ratings and host since

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-08 14:09:14.437857

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('apartments', sa.Column('reviews_count', sa.Integer(), nullable=True))
    op.add_column('site_settings', sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('site_settings', sa.Column('reviews_count', sa.Integer(), nullable=True))
    op.add_column('site_settings', sa.Column('host_since_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'host_since_year')
    op.drop_column('site_settings', 'reviews_count')
    op.drop_column('site_settings', 'rating')
    op.drop_column('apartments', 'reviews_count')
    op.drop_column('apartments', 'rating')
    # ### end Alembic commands ###
